import { Suspense } from "react";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { Toaster } from "sonner";
import StyledComponentsRegistry from "./core/lib/registry";
import QueryProvider from "./core/providers/QueryProvider";
import ThemeProvider from "./core/providers/ThemesProvider";
import "./globals.css";
import Loader from "./components/Loader";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Aqila",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${outfit.className} bg-white dark:bg-black text-white dark:text-[#fffff]`}>
        <StyledComponentsRegistry>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange>
              <Suspense fallback={<Loader />}>
                {children}
                <Toaster
                  richColors
                  position="top-right"
                  expand={true}
                  duration={3000}
                />
              </Suspense>
            </ThemeProvider>
          </QueryProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
